#!/bin/bash

set -e

export variant=$2
export version=$3

if [[ "$EUID" -ne 0 ]]; then
	echo -e "Run this script as root"
	exit 1
fi

function explaination() {
	echo -e "Kaisen Linux ISO build

USAGE
 	 sudo ./kaisen-build <action> <variant> <version>

EXPLAINATION

      action  - help, build, clean
                help : display help
		build : build iso
		clean : clean residual files

      variant - MATE, XFCE, KDE, LXDE, SR, CUSTOM
		the graphical interface to use (or usr SR release)

      version - select your version number

EXAMPLE
 	 sudo ./kaisen-build build CUSTOM 1.0
      or sudo ./kaisen-build build CUSTOM
"
}

function kaisen-build() {
	lb build
	case $variant in
		KDE|LXDE|MATE|XFCE|SR)
	mv live-image-amd64.hybrid.iso ../kaisenlinuxrolling$version-amd64-$variant.iso
	;;
	esac
	case $variant in
                CUSTOM)
        mv live-image-amd64.hybrid.iso ../kaisenlinuxCUSTOM-amd64-$version.iso
        ;;
        esac
	lb clean
	rm -rf cache config .build || true
}

function clean() {
	lb clean
	rm -rf cache config unpacked-initrd .build || true
}

case $1 in
        build)
                kaisen-build
        ;;
	clean)
		clean
	;;
        help)
                explaination
        ;;
        *)
                explaination
        ;;
esac
