#!/bin/bash

set -e

case "$1" in
	upgrade|full-upgrade|remove|autoremove|downgrade|abort-upgrade)
    find /home/*/kaisen-build/auto -delete 2>&1 /dev/null || true
    find /home/*/kaisen-build/common -delete 2>&1 /dev/null || true
    find /home/*/kaisen-build/variant/KDE -delete 2>&1 /dev/null || true
    find /home/*/kaisen-build/variant/LXDE -delete 2>&1 /dev/null || true
    find /home/*/kaisen-build/variant/MATE -delete 2>&1 /dev/null || true
    find /home/*/kaisen-build/variant/XFCE -delete 2>&1 /dev/null || true
    find /home/*/kaisen-build/variant/SR -delete 2>&1 /dev/null || true
    find /home/*/kaisen-build/kaisen-build -delete 2>&1 /dev/null || true
;;
esac

if [[ "$1" = "purge" ]]; then
	find /home/*/kaisen-build -delete > /dev/null 2>&1 || true
fi

#DEBHELPER
