#!/bin/bash

set -e

case "$1" in
	upgrade|full-upgrade|remove|autoremove|downgrade|abort-upgrade)
    find /home/*/kaisen-build/auto -delete > /dev/null 2>&1 || true
    find /home/*/kaisen-build/common -delete > /dev/null 2>&1 || true
    find /home/*/kaisen-build/variant/KDE -delete > /dev/null 2>&1 || true
    find /home/*/kaisen-build/variant/LXDE -delete > /dev/null 2>&1 || true
    find /home/*/kaisen-build/variant/MATE -delete > /dev/null 2>&1 || true
    find /home/*/kaisen-build/variant/XFCE -delete > /dev/null 2>&1 || true
    find /home/*/kaisen-build/variant/SR -delete > /dev/null 2>&1 || true
    find /home/*/kaisen-build/kaisen-build -delete > /dev/null 2>&1 || true
;;
esac

if [[ "$1" = "purge" ]]; then
	find /home/*/kaisen-build -delete > /dev/null 2>&1 || true
fi

#DEBHELPER
