#!/bin/bash

set -e

if [[ "$1" = "configure" ]]; then

	for users in $(awk -F: '/\/home/ {printf "%s:%s\n",$1,$3}' /etc/passwd | cut -d: -f1)
	do
		cp -rf /tmp/kaisen-build /home/$users/ && chown -R $users: /home/$users/kaisen-build || true
		cp -rf /usr/share/kaisen-build/$users/CUSTOM /home/$users/kaisen-build/variant/ 2> /dev/null || true
	done

fi

#DEBHELPER
