#!/bin/bash

set -e

for users in $(awk -F: '/\/home/ {printf "%s:%s\n",$1,$3}' /etc/passwd | cut -d: -f1)
do
	mkdir -p /usr/share/kaisen-build/$users 2> /dev/null || true
	cp -rf /home/$users/kaisen-build/variant/CUSTOM /usr/share/kaisen-build/$users/ 2> /dev/null || true
done

#DEBHELPER
