#!/bin/bash

#ISO build script for Kaisen Linux

set -e

params=""

mkdir config || true
cp -rf common/* config
cp -rfTL variant/$variant config

case $variant in
        KDE|LXDE|MATE|XFCE)
	params="$params --debian-installer live --debian-installer-distribution kaisen-rolling --debian-installer-gui true --iso-preparer Kaisen --iso-publisher Kaisen --loadlin true --win32-loader true --system live"
        ;;
        SR)
	params="$params --debian-installer none --iso-preparer Kaisen --iso-publisher Kaisen --system live"
        ;;
	CUSTOM)
	params="$params --debian-installer live --debian-installer-distribution kaisen-rolling --debian-installer-gui true --iso-preparer Personal --iso-publisher Personal --loadlin true --win32-loader true --system live"
esac

lb config noauto \
--apt "apt" \
--apt-indices "true" \
--apt-recommends "true" \
--apt-secure "true" \
--architecture "amd64" \
--archive-areas "main contrib non-free" \
--binary-images  "iso-hybrid" \
--binary-filesystem "fat32" \
--build-with-chroot "true" \
--bootloaders "syslinux,grub-efi" \
--cache "true" \
--cache-indices "true" \
--cache-packages "true" \
--cache-stages "bootstrap" \
--checksums "sha256" \
--clean \
--distribution "kaisen-rolling" \
--distribution-binary "kaisen-rolling" \
--distribution-chroot "kaisen-rolling" \
--firmware-binary "true" \
--firmware-chroot "true" \
--iso-application "Kaisen Linux Rolling $variant $version" \
--iso-volume "Kaisen Linux Rolling $variant $version" \
--linux-flavours "amd64" \
--linux-packages "linux-image" \
--keyring-package "kaisen-archive-keyring" \
--memtest "memtest86+" \
--security "false" \
--source "false" \
--uefi-secure-boot "disable" \
--backports "false" \
--updates "false" \
--verbose \
--parent-mirror-bootstrap "https://kaisendeb.lf.je/kaisen" \
--parent-mirror-chroot "https://kaisendeb.lf.je/kaisen" \
--parent-mirror-binary "https://kaisendeb.lf.je/kaisen" \
--parent-mirror-debian-installer "https://kaisendeb.lf.je/kaisen" \
--mirror-bootstrap "https://kaisendeb.lf.je/kaisen" \
--mirror-chroot "https://kaisendeb.lf.je/kaisen" \
--mirror-binary "https://kaisendeb.lf.je/kaisen" \
--mirror-debian-installer "https://kaisendeb.lf.je/kaisen" \
--parent-archive-areas "main contrib non-free" \
$params \
