#!/bin/bash

#ISO build script for Kaisen Linux

set -e

PARAMS=""

mkdir config || true

if [[ "$VARIANT" = "KDE" || "$VARIANT" = "LXDE" || "$VARIANT" = "MATE" || "$VARIANT" = "XFCE" || "$VARIANT" = "SR" ]]; then
cp -rf common/* config
cp -rfTL variant/$VARIANT config
elif [[ "$VARIANT" = "CONSOLE" ]]; then
cp -rf common/* config
cp -rf variant/CONSOLE/* config
rm config/package-lists/guests.list.chroot
elif [[ "$VARIANT" = "CUSTOM" ]]; then
cp -rf variant/CUSTOM/* config
fi

case $VARIANT in
        KDE|LXDE|MATE|XFCE)
	PARAMS="$PARAMS --debian-installer live --debian-installer-distribution kaisen-rolling --debian-installer-gui true --loadlin true --win32-loader true --system live --firmware-binary true --firmware-chroot true"
        ;;
        SR)
	PARAMS="$PARAMS --debian-installer none --system live --firmware-binary true --firmware-chroot true"
	;;
	CONSOLE)
	PARAMS="$PARAMS --debian-installer none --system live --firmware-binary false --firmware-chroot false"
        ;;
	CUSTOM)
	PARAMS="$PARAMS --debian-installer live --debian-installer-distribution kaisen-rolling --debian-installer-gui true --iso-preparer Personal --iso-publisher Personal --loadlin true --win32-loader true --system live --firmware-binary true --firmware-chroot true"
	;;
esac

lb config noauto \
--apt "apt" \
--apt-indices "true" \
--apt-recommends "true" \
--apt-secure "true" \
--architecture "amd64" \
--archive-areas "main contrib non-free" \
--binary-images  "iso-hybrid" \
--binary-filesystem "fat32" \
--build-with-chroot "true" \
--bootloaders "syslinux,grub-efi" \
--cache "true" \
--cache-indices "true" \
--cache-packages "true" \
--cache-stages "bootstrap" \
--checksums "sha256" \
--clean \
--distribution "kaisen-rolling" \
--distribution-binary "kaisen-rolling" \
--distribution-chroot "kaisen-rolling" \
--iso-preparer "Kevin Chevreuil - Kaisen" \
--iso-publisher "Kevin Chevreuil - Kaisen" \
--iso-application "Kaisen Linux $VARIANT $VERSION" \
--iso-volume "Kaisen Linux $VARIANT $VERSION" \
--linux-flavours "amd64" \
--linux-packages "linux-image" \
--keyring-package "kaisen-archive-keyring" \
--memtest "memtest86+" \
--security "false" \
--source "false" \
--uefi-secure-boot "disable" \
--backports "false" \
--updates "false" \
--verbose \
--parent-mirror-bootstrap "https://deb.kaisenlinux.org" \
--parent-mirror-chroot "https://deb.kaisenlinux.org" \
--parent-mirror-binary "https://deb.kaisenlinux.org" \
--parent-mirror-debian-installer "https://deb.kaisenlinux.org" \
--mirror-bootstrap "https://deb.kaisenlinux.org" \
--mirror-chroot "https://deb.kaisenlinux.org" \
--mirror-binary "https://deb.kaisenlinux.org" \
--mirror-debian-installer "https://deb.kaisenlinux.org" \
--parent-archive-areas "main contrib non-free" \
$PARAMS \
