#!/bin/bash

#ISO build script for Kaisen Linux

set -e

params=""

cp -rfTL variant/$variant config
cp -rf common/* config

case $variant in
        KDE|LXDE|MATE|XFCE)
	params="$params --debian-installer live --debian-installer-distribution kaisen-rolling --debian-installer-gui true"
        ;;
        SR)
	params="$params --debian-installer false"
        ;;
esac

case $variant in
        KDE|LXDE|MATE|XFCE)
	params="$params --iso-application Kaisen Linux Rolling $variant $version --iso-volume Kaisen Linux Rolling $variant $version"
        ;;
        SR)
	params="$params --iso-application Kaisen Linux SystemRescue --iso-volume Kaisen Linux SystemRescue"
	;;
esac

lb config noauto \
--apt "apt" \
--apt-indices "true" \
--apt-recommends "true" \
--apt-secure "true" \
--architectures "amd64" \
--archive-areas "main contrib non-free" \
--binary-images  "iso-hybrid" \
--binary-filesystem "fat32" \
--build-with-chroot "true" \
--bootloaders "syslinux,grub-efi" \
--cache "true" \
--cache-indices "yes" \
--cache-packages "true" \
--cache-stages "bootstrap" \
--checksums "sha256" \
--clean \
--distribution "kaisen-rolling" \
--distribution-binary "kaisen-rolling" \
--distribution-chroot "kaisen-rolling" \
--firmware-binary "true" \
--firmware-chroot "true" \
--linux-flavours "amd64" \
--linux-packages "linux-image" \
--loadlin "true" \
--iso-preparer "Kevin Chevreuil - Kaisen" \
--iso-publisher "Kevin Chevreuil - Kaisen" \
--keyring-package "kaisen-archive-keyring" \
--memtest "memtest86+" \
--security "false" \
--source "false" \
--system "live" \
--uefi-secure-boot "disable" \
--backports "false" \
--updates "false" \
--verbose \
--win32-loader "true" \
--parent-mirror-bootstrap "https://kaisendeb.lf.je/kaisen" \
--parent-mirror-chroot "https://kaisendeb.lf.je/kaisen" \
--parent-mirror-binary "https://kaisendeb.lf.je/kaisen" \
--parent-mirror-debian-installer "https://kaisendeb.lf.je/kaisen" \
--mirror-bootstrap "https://kaisendeb.lf.je/kaisen" \
--mirror-chroot "https://kaisendeb.lf.je/kaisen" \
--mirror-binary "https://kaisendeb.lf.je/kaisen" \
--mirror-debian-installer "https://kaisendeb.lf.je/kaisen" \
--parent-archive-areas "main contrib non-free" \
$params \
