#!/bin/bash

set -e

DISKNUM=$3
CDDIR=$4
BASEDIR=$(pwd)

cd $CDDIR

change_text() {
    sed -i -e 's|_Debian GNU/Linux installer menu (BIOS mode)|Kaisen Linux Rolling NETINST
	-e 's|Kaisen GNU/Linux Rolling|Kaisen Linux Rolling NETINST
	-e 's|Debian GNU/Linux|Kaisen GNU/Linux|g' \
	"$@"
}

if [ -e ../boot$DISKNUM/isolinux/menu.cfg ]; then
    change_text ../boot$DISKNUM/isolinux/menu.cfg \
		 ../boot$DISKNUM/isolinux/*.txt
fi
if [ -d boot/grub/theme ] && [ -s boot/grub/theme ]; then
    change_text boot/grub/theme/*
fi
if [ -e autorun.inf ]; then
    change_text autorun.inf
fi
